model_params:
  name: 'GaussianVae'
  base: 'VaeBase'

architecture:
  img_encoder: 'ConvEncoder224x224'
  img_decoder: 'ConvDecoder224x224'

img_arch_params:
  in_channels: 3
<<<<<<< HEAD:configs/xx_archive/vae_adidas.yaml
  latent_dim: 20
=======
  latent_dim: 50
>>>>>>> e1bf9a75934527ab51b1d8af923ad40d0da5af4a:configs/adidas/vae_adidas.yaml

exp_params:
  dataset: 'adidas'
  data_path: "data/"
  img_size: 224
  batch_size: 64
  learning_rate: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "GaussianVae"
  manual_seed: 1265
