model_params:
  name: 'InfoVae'
  base: 'VaeBase'

architecture:
  img_encoder: 'ConvEncoder'
  img_decoder: 'ConvDecoder'

img_arch_params:
  in_channels: 1
  img_size: 28
  latent_dim: 10 
  enc_hidden_dims: [32, 64, 128, 256]
  enc_kernel_size: [3, 3, 3, 3]
  enc_stride: [2, 2, 2, 2]
  enc_padding: [1, 1, 1, 1]
  dec_hidden_dims: [256, 128, 64, 32]
  dec_kernel_size: [3, 3, 3, 2]
  dec_stride: [2, 2, 2, 2]
  dec_padding: [1, 1, 1, 2]
  dec_out_padding: [1, 1, 1]

exp_params:
  dataset: 'mnist'
  data_path: "data/"
  img_size: 28
  batch_size: 32
  learning_rate: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 2

logging_params:
  save_dir: "logs/"
  name: "InfoVae"
  manual_seed: 1265