model_params:
  name: 'InfoVae'
  base: 'VaeBase'

architecture:
  img_encoder: 'ConvEncoder28x28'
  img_decoder: 'ConvDecoder28x28'

img_arch_params:
  in_channels: 1
  latent_dim: 10

exp_params:
  dataset: 'fashionmnist'
  data_path: "data/"
  img_size: 28
  batch_size: 32
  learning_rate: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: "InfoVae"
  manual_seed: 1265