model_params:
  name: 'CatVae'
  base: 'VaeBase'

model_hyperparams:
  temperature: 0.5
  anneal_rate: 0.00003
  anneal_interval: 100
  alpha: 30.
  probability: True

architecture:
  img_encoder: 'ConvEncoder224x224'
  img_decoder: 'ConvDecoder224x224'

img_arch_params:
  in_channels: 3
  latent_dim: 40
  categorical_dim: 10

exp_params:
  dataset: 'adidas'
  data_path: "data/"
  img_size: 28
  batch_size: 32
  learning_rate: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "CatVae"
  manual_seed: 1265
